benchmark_root: /mnt/data2/lfwj/wall-x4juliang/LIBERO/libero/libero
bddl_files: /mnt/data2/lfwj/wall-x4juliang/LIBERO/libero/libero/bddl_files
init_states: /mnt/data2/lfwj/wall-x4juliang/LIBERO/libero/libero/init_files
datasets: /mnt/data2/lfwj/wall-x4juliang/LIBERO/datasets
assets: /mnt/data2/lfwj/wall-x4juliang/LIBERO/libero/libero/assets
